version: '3'
services:
    music-backend:
        container_name: rust-practice
        image: rust-practice
        env_file:
            - .env
        build:
            context: .
            dockerfile: rust/Dockerfile
        volumes:
            - ..:/workspace
        tty: true
        environment:
            - TZ=Asia/Tokyo
        working_dir: /workspace
            - db

    db:
        container_name: rust-db
        build: db/Dockerfile
        restart: always
        volumes:
            - ../db/:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
        environment:
        POSTGRES_USER: "goemon"
        POSTGRES_PASSWORD: "password"