version: '3'
services:
    rust-practice:
        container_name: rust-practice
        image: rust-practice
        env_file:
            - .env
        build:
            context: .
            dockerfile: rust/Dockerfile
        volumes:
            - ..:/workspace
        tty: true
        environment:
            - TZ=Asia/Tokyo
        working_dir: /workspace
            - db

    db:
        container_name: rust-db
        build:
            context: .
            dockerfile: db/Dockerfile
        env_file:
            - .env
        restart: always
        volumes:
            - ../db/:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
